format_version: v1.0
type: UniqueComponent
attributes: {id: sysWifiPic32mzw1}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: SYS_WIFI_AP_CHANNEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '6'}
  - type: String
    attributes: {id: SYS_WIFI_AP_PWD_NAME}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: password}
  - type: String
    attributes: {id: SYS_WIFI_AP_SSID_NAME}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DEMO_AP_SOFTAP}
  - type: Combo
    attributes: {id: SYS_WIFI_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: AP}
  - type: Boolean
    attributes: {id: SYS_WIFI_PROVISION_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: SYS_WIFI_STA_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '259', y: '51', id: sysWifiPic32mzw1}
